version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/netrav_backend:latest
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - docs:/app/api/docs/
    depends_on:
      - db

  nginx:
    image: ${{ secrets.DOCKER_USERNAME }}/netrav_gateway:latest
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../csv/Artists.csv
      - ../csv/Association_Members.csv
      - ../csv/Association_Owners.csv
      - ../csv/Associations.csv
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
