# Generated by Django 3.1.4 on 2024-06-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('is_artist', models.BooleanField(default=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('death_place', models.CharField(blank=True, max_length=255, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('wiki_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('work_start', models.IntegerField(blank=True, null=True)),
                ('work_end', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.association')),
            ],
            options={
                'unique_together': {('artist', 'association')},
            },
        ),
        migrations.CreateModel(
            name='MemberAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.association')),
            ],
            options={
                'unique_together': {('artist', 'association')},
            },
        ),
        migrations.CreateModel(
            name='ArtistArtMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artmovement')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
            options={
                'unique_together': {('artist', 'art_movement')},
            },
        ),
    ]
