# Generated by Django 4.2.13 on 2024-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('isArtist', models.BooleanField(default=True)),
                ('birthDate', models.CharField(blank=True, max_length=255, null=True)),
                ('deathDate', models.CharField(blank=True, max_length=255, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('deathPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
                ('wikiUrl', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('workStart', models.IntegerField(blank=True, null=True)),
                ('workEnd', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='AssociationMembers', to='artists.artist')),
                ('owners', models.ManyToManyField(blank=True, related_name='AssociationOwners', to='artists.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='artMovements',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artists.artmovement'),
        ),
    ]
