# Generated by Django 4.2.13 on 2024-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='Association_Members', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='association',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='Association_Owners', to='artists.artist'),
        ),
    ]
