# Generated by Django 4.2.13 on 2024-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_association_members_alter_association_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='otherInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
