# Generated by Django 3.1.4 on 2024-06-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20240605_0309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownerassociation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ownerassociation',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='ownerassociation',
            name='association',
        ),
        migrations.AddField(
            model_name='association',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_associations', to='artists.Artist'),
        ),
        migrations.AddField(
            model_name='association',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owner_associations', to='artists.Artist'),
        ),
        migrations.DeleteModel(
            name='MemberAssociation',
        ),
        migrations.DeleteModel(
            name='OwnerAssociation',
        ),
    ]
