# Generated by Django 4.2.13 on 2024-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_association_otherinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='workEnd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='workStart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
